name: globe_cast_meetings

description: A flutter app
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  auto_route: ^10.0.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.2
  phosphor_flutter: ^2.1.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  path: ^1.9.1
  gap: ^3.0.1
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2
  scabld_safe_area_insets: ^1.0.0
  http: ^1.4.0
  permission_handler: ^12.0.0+1
  flutter_webrtc: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.2.3
  build_runner: any
  freezed: ^3.0.2
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  generate: true
  #assets:
   # - assets/files/
    #- assets/icons/
    #- assets/images/
